const mockData = [
    // [
    //     'https://miro.medium.com/v2/resize:fit:439/1*ZYyXvhYDGvELzYoXYpPLMg.png',
    //     'designers programmers idea stole',
    //     'G:/Gallery/images/memes/programming/designers.png',
    //     'designers.png',
    //     '20.09.2019'
    // ],
    // [
    //     'https://miro.medium.com/v2/resize:fit:600/format:webp/0*Y602BVKpn-ek3V5P.png',
    //     'non-programmers programming meme',
    //     'G:/Gallery/images/memes/programming/programming.png',
    //     'programming.png',
    //     '21.10.2017',
    // ],
    // [
    //     'https://i.redd.it/m82c4lsz0hb31.jpg',
    //     'your mama binary tree time complexity',
    //     'G:/Gallery/images/memes/programming/binary_tree_mom.png',
    //     'binary_tree_mom.png',
    //     '23.01.2018',
    // ],
    // [
    //     'https://miro.medium.com/v2/resize:fit:600/format:webp/0*o7iRGMHGNO6JbTg3.png',
    //     'stack overflow',
    //     'G:/Gallery/images/memes/programming/stack_overflow.png',
    //     'stack_overflow.png',
    //     '22.02.2022',
    // ],
    // [
    //     'https://miro.medium.com/v2/resize:fit:600/format:webp/0*NsfFeu-AcAPlBl6z.png',
    //     'someone else code',
    //     'G:/Gallery/images/memes/programming/someone_else_code.png',
    //     'someone_else_code.png',
    //     '21.01.2021',
    // ],
    // [
    //     'https://miro.medium.com/v2/resize:fit:786/0*PgiLG7NytqKAh8WT.',
    //     'bubble sort time complexity',
    //     'G:/Gallery/images/memes/programming/bubble_sort.png',
    //     'bubble_sort.png',
    //     '02.02.2022',
    // ],
    // [
    //     'https://www.google.com/url?sa=i&url=https%3A%2F%2Fapoorvtyagi.tech%2Fimproving-time-complexity&psig=AOvVaw3uHtR5wKffUVONSWAW7eVD&ust=1684752599992000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCMizktSehv8CFQAAAAAdAAAAABAE',
    //     'time complexity input',
    //     'G:/Gallery/images/memes/programming/input.png',
    //     'input.png',
    //     '01.03.2022',
    // ],
    // [
    //     'https://img.devrant.com/devrant/rant/r_1204944_6PfxU.jpg',
    //     'time complexity',
    //     'G:/Gallery/images/memes/programming/time_complexity.png',
    //     'time_complexity.png',
    //     '01.01.2021',
    // ],
    // [
    //     'https://pbs.twimg.com/media/EW-nGXGWsAEMK4v.jpg',
    //     'time complexity javascript meme',
    //     'G:/Gallery/images/memes/programming/javascript_meme.png',
    //     'javascript_meme.png',
    //     '10.01.2019',
    // ],
    // [
    //     'https://b1694534.smushcdn.com/1694534/wp-content/uploads/2021/06/7-1017x1024.png?lossy=1&strip=1&webp=1',
    //     'framework javascript meme',
    //     'G:/Gallery/images/memes/programming/framework_js_meme.png',
    //     'framework_js_meme.png',
    //     '11.03.2019',
    // ],
    // [
    //     'https://www.freecodecamp.org/news/content/images/2019/07/panel-1-1.png',
    //     'equation javascript meme',
    //     'G:/Gallery/images/memes/programming/framework_js_meme.png',
    //     'framework_js_meme.png',
    //     '11.03.2019',
    // ],
    // [
    //     'https://b1694534.smushcdn.com/1694534/wp-content/uploads/2021/06/2.jpeg?lossy=1&strip=1&webp=1',
    //     'most programming language javascript meme',
    //     'G:/Gallery/images/memes/programming/js_best_language_meme.png',
    //     'js_best_language_meme.png',
    //     '15.04.2020',
    // ],
    // [
    //     'https://blog.webix.com/wp-content/uploads/2021/07/2.jpg',
    //     'html programming meme',
    //     'G:/Gallery/images/memes/programming/html_meme.png',
    //     'html_meme.png',
    //     '10.07.2020',
    // ],
    // [
    //     'https://www.freecodecamp.org/news/content/images/2019/07/panel-3-1.png',
    //     'javascript meme',
    //     'G:/Gallery/images/memes/programming/js_meme.png',
    //     'js_meme.png',
    //     '13.05.2020',
    // ],
    // [
    //     'https://preview.redd.it/w62g1tovijh21.jpg?auto=webp&s=ef4809ca486ef1bc72e38c4d075a29a1d890f326',
    //     'python c++ meme',
    //     'G:/Gallery/images/memes/programming/python_c++.png',
    //     'python_c++.png',
    //     '17.05.2022',
    // ],
];

export { mockData };